---
- name: Validate Docker project configuration
  ansible.builtin.assert:
    that:
      - docker_projects is defined
      - docker_projects | length > 0
    fail_msg: "No Docker projects defined"

- name: Filter excluded projects
  ansible.builtin.set_fact:
    docker_projects_filtered: "{{ docker_projects | rejectattr('name', 'in', docker_projects_exclude) | list }}"

- name: Debug excluded projects
  ansible.builtin.debug:
    msg: "Excluding projects: {{ docker_projects_exclude | join(', ') }}"
  when: docker_projects_exclude | length > 0

- name: Find Docker Compose Files
  ansible.builtin.find:
    paths: "{{ docker_project_root }}/{{ item.name }}"
    patterns:
      - 'compose.{{ item.name }}.yml'
      - 'compose.{{ item.name }}.yaml'
      - '{{ item.name }}.compose.yml'
      - '{{ item.name }}.compose.yaml'
      - 'docker-compose.yml'
      - 'docker-compose.yaml'
      - 'compose.yml'
      - 'compose.yaml'
  register: compose_files
  loop: "{{ docker_projects_filtered }}"
  loop_control:
    label: "{{ item.name }}"
